/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class TaskCloudDB {
    constructor() {
        this.id = undefined;
        this.title = "";
        this.description = undefined;
        this.status = "";
        this.priority = "";
        this.dueDate = undefined;
        this.createTime = "";
        this.updateTime = "";
        this.completedTime = undefined;
        this.tags = "";
        this.userld = "";
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setTitle(title) {
        this.title = title;
    }

    getTitle() {
        return this.title;
    }

    setDescription(description) {
        this.description = description;
    }

    getDescription() {
        return this.description;
    }

    setStatus(status) {
        this.status = status;
    }

    getStatus() {
        return this.status;
    }

    setPriority(priority) {
        this.priority = priority;
    }

    getPriority() {
        return this.priority;
    }

    setDueDate(dueDate) {
        this.dueDate = dueDate;
    }

    getDueDate() {
        return this.dueDate;
    }

    setCreateTime(createTime) {
        this.createTime = createTime;
    }

    getCreateTime() {
        return this.createTime;
    }

    setUpdateTime(updateTime) {
        this.updateTime = updateTime;
    }

    getUpdateTime() {
        return this.updateTime;
    }

    setCompletedTime(completedTime) {
        this.completedTime = completedTime;
    }

    getCompletedTime() {
        return this.completedTime;
    }

    setTags(tags) {
        this.tags = tags;
    }

    getTags() {
        return this.tags;
    }

    setUserld(userld) {
        this.userld = userld;
    }

    getUserld() {
        return this.userld;
    }
}

TaskCloudDB.className = 'TaskCloudDB';

export {TaskCloudDB}