/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class BillCloudDB {
    constructor() {
        this.id = undefined;
        this.type = "";
        this.category = "";
        this.amount = "";
        this.description = undefined;
        this.date = "";
        this.createTime = "";
        this.updateTime = "";
        this.tags = "";
        this.userId = "";
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setType(type) {
        this.type = type;
    }

    getType() {
        return this.type;
    }

    setCategory(category) {
        this.category = category;
    }

    getCategory() {
        return this.category;
    }

    setAmount(amount) {
        this.amount = amount;
    }

    getAmount() {
        return this.amount;
    }

    setDescription(description) {
        this.description = description;
    }

    getDescription() {
        return this.description;
    }

    setDate(date) {
        this.date = date;
    }

    getDate() {
        return this.date;
    }

    setCreateTime(createTime) {
        this.createTime = createTime;
    }

    getCreateTime() {
        return this.createTime;
    }

    setUpdateTime(updateTime) {
        this.updateTime = updateTime;
    }

    getUpdateTime() {
        return this.updateTime;
    }

    setTags(tags) {
        this.tags = tags;
    }

    getTags() {
        return this.tags;
    }

    setUserId(userId) {
        this.userId = userId;
    }

    getUserId() {
        return this.userId;
    }
}

BillCloudDB.className = 'BillCloudDB';

export {BillCloudDB}